package Task;

public enum TaskState { // 即將要實作, 這目前是重點
    BOSS_RELEASE,
    WORKER_WORKING,
    BOSS_DONE_CHECK,
    BOSS_CHECK_PASS,
    BOSS_CHECK_NOT_PASS,
    CLOSE_AN_ACCOUNT_REWARD,
    COORDINATION,
    BOSS_REQUEST_STOP_TASK,
    BOSS_CANCEL_STOP_TASK_REQUEST,
    WORKER_AGREE_STOP_TASK,
    WORKER_NOT_AGREE_STOP_TASK,
    END
}
